title: Addis Studio
baseurl: /
permalink: '/:title/'
palette: blue
header:
  has_nav: true
  logo_img: /images/Cream with Cassette Tape Music Logo.png
  menu:
    actions:
      - label: Sign Up
        url: /signup
  title: Addis Studio
footer:
  subscribe_title: Subscribe
  subscribe_content: Stay up to date with our latest developments.
  has_subscribe: true
  social_title: Community
  tagline: ''
  logo_img: /images/Cream with Cassette Tape Music Logo(2).png
  has_social: true
  content: '&copy; Addis Studio. All rights reserved.'
  links:
    - new_window: false
      text: Website Designed by Sheger Tech
      url: 'https://shegertech.com'
  nav_title: Company
  has_nav: true
sass:
  indentWidth: 4
  precision: 10
  style: nested
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
